name: Render PlantUML
description: Render PlantUML diagrams

inputs:
  files:
    required: true
    description: Pattern of files to render

runs:
  using: docker
  image: runtime/Dockerfile
  args:
    - ${{ inputs.files }}
