name: Render PlantUML
description: Render PlantUML diagrams
author: Felix Klauke <felix@klauke-enterprises.com>

branding:
  icon: book

inputs:
  files:
    required: true
    description: Pattern of files to render

runs:
  using: docker
  image: runtime/Dockerfile
  args:
    - ${{ inputs.files }}
